mysite/camaras/urls.py
from django.urls import path 
from django.conf.urls import include, url
from django.views.generic import TemplateView
from camaras.views import  ( alarma_post,
                            alarma_inst,
                            eventos,
                            eventos_list,
                            upd_envio,
                            cam_disp,
                            camviva_post,
                            cam_down,
                            licencia,
                            )

urlpatterns = [
path('api/alarma/', alarma_post, name='alarma_post'),
path('api/cam_down/', cam_down, name='cam_down'),
path('api/cam_disp/<int:id>/', cam_disp, name='cam_disp'),
path('api/camviva/', camviva_post, name='camviva_post'),
path('ajax/alarmas/', alarma_inst, name='alarma_inst'),
path('alarmas/eventos', eventos_list, name='eventos_list'),
path('alarmas/eventos/<int:id>/', eventos, name='eventos'),
path('ajax/upd_envio/', upd_envio, name='upd_envio'),
#path('sobre/', TemplateView.as_view(template_name="sobre.html")),
path('sobre/', licencia, name='licencia'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path 
from django.conf.urls import include, url
from camaras.views import home, camara, lista_camaras, lista_alarmas, video, borra_alarmas
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #path('accounts/', include('accounts.urls')), # new
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('camaras.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('camara/<int:id>', camara, name='camara'),
    path('camara/', lista_camaras, name='lista_camaras'),
    path('alarmas/', lista_alarmas, name='lista_alarmas'),
    path('borra_alarmas/', borra_alarmas, name='borra_alarmas'),
    path('video/<int:id>/', video, name='video'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/camaras/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import uuid
from django import forms

# Create your models here.
class Camara(models.Model):
    nombre = models.CharField(max_length=10)
    estado = models.BooleanField(default=False)
    sensib = models.IntegerField('Sensibilidad det')
    fuente = models.CharField(max_length=300)
    image = models.BinaryField(blank=True)
    actualizado = models.DateTimeField('Actualizado',blank=True, null=True,auto_now_add=False)
    areas = models.TextField('Areas',blank=True, null=True)
    op_ini = models.TimeField('Inicio turno',blank=True, null=True,auto_now_add=False, editable=True)
    op_fin = models.TimeField('Fin turno',blank=True, null=True,auto_now_add=False, editable=True)
    secreto = models.CharField(max_length=50, default=uuid.uuid4().hex, null=False, blank=False, editable=False, unique=False)
    #url_alarm = models.CharField(max_length=300,)
    detect_todo = models.BooleanField('Detecta toda la pantalla',default=False)
    min_contour_width=models.IntegerField('min_contour_width', default=20,null=False, blank=False)
    min_contour_height=models.IntegerField('min_contour_height', default=20,null=False, blank=False)
    max_contour_width=models.IntegerField('max_contour_width', default=590,null=False, blank=False)
    max_contour_height=models.IntegerField('max_contour_height', default=590,null=False, blank=False)
    dist_bg = models.IntegerField('Distancia recorrida px', default=290)
    rep_alar_ni = models.IntegerField('Rep alarm en fr', default=20)
    error_msg = models.CharField('Msg error',blank=True, null=True,max_length=300)
    min_area_mean = models.IntegerField('Área min prom', blank=True, null=True)
    time_min = models.TimeField('Tiempo mín',auto_now=False, auto_now_add=False, blank=True, null=True  )
    #Parametros vivotek
    cam_model = models.CharField('Modelo',blank=True, null=True,max_length=30)
    host=models.CharField('cam host',blank=True, null=True,max_length=15, default='0.0.0.0')
    port=models.IntegerField('cam port', default=443)
    usr=models.CharField('cam usr',blank=True, null=True,max_length=25, default='worker_st')
    pwd=models.CharField('cam pwd',blank=True, null=True,max_length=35)
    digest_auth=models.BooleanField('cam digest_auth',default=True)
    ssl=models.BooleanField('cam ssl',default=False)
    verify_ssl=models.BooleanField('cam verify_ssl',default=False)
    sec_lvl=models.CharField('cam sec_lvl',blank=True, null=True,max_length=25, default='operator')

    class Meta:
        verbose_name_plural = "Cámaras"

    # def save(self, *args, **kwargs):
    #     self.secreto = uuid.uuid4().hex
    #     super(Camara, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.nombre)

class Alarmas(models.Model):
    camara = models.ForeignKey('Camara', on_delete=models.PROTECT)
    tiempo = models.DateTimeField('Fecha hora',auto_now_add=False)
    clase = models.CharField(max_length=300)
    cantidad = models.IntegerField()
    video = models.CharField(max_length=300)
    recibido = models.DateTimeField('Recibido',blank=True, null=True,auto_now_add=False)
    evento = models.ForeignKey('Eventos',blank=True, null=True, on_delete=models.PROTECT)


    class Meta:
        verbose_name_plural = "Alarmas"

    def __str__(self):
        return str(self.camara)

class Eventos(models.Model):
    """docstring for ClassName"""
    t_ini = models.DateTimeField('Fecha hora inicio',auto_now_add=True)
    t_fin = models.DateTimeField('Fecha hora termino',auto_now_add=False, blank=True, null=True)
    activo = models.BooleanField('Alarma activa',default=True)
    proced = models.BooleanField('En prodedimiento',default=False)
    estado = models.IntegerField('Nivel escalamiento',default=0)
    #responsable = models.ForeignKey(User,blank=True, null=True,on_delete=models.PROTECT)
    responsable = models.TextField('Responsable',blank=True, null=True)
    comentarios = models.TextField('Comentarios',blank=True, null=True)

    class Meta:
        verbose_name_plural = "Eventos"

    def __str__(self):
        return str(self.t_ini)

class RegAcciones(models.Model):
    tiempo = models.DateTimeField('Fecha hora accion',auto_now_add=True)
    accion = models.CharField('Acciones',max_length=300)
    evento = models.ForeignKey('Eventos',blank=True, null=True, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Acciones"

class Responsables(models.Model):
    TIPO = [
        ('SMS','SMS'),
        ('EMAIL','EMAIL'),
        ('ENDPOINT','ENDPOINT'),
         ]

    LEVEL = [
        (0,'Nivel 0'),
        (1,'Nivel 1'),
        (2,'Nivel 2'),
        (3,'Nivel 3'),
         ]
    nombre = models.CharField('Nombre',max_length=100)
    fono = models.CharField('Fono cell',max_length=20,blank=True, null=True,)
    mail = models.CharField('eMail',max_length=90,blank=True, null=True,)
    nivel = models.IntegerField('Nivel alarma',choices=LEVEL ,default=0)
    tipo = models.CharField("Tipo acciones",choices=TIPO ,max_length=60, unique=False)
    endpoint = models.CharField('uri',max_length=300, blank=True, null=True,)
    estado = models.BooleanField('Estado',default=True)

    class Meta:
        verbose_name_plural = "Responsables"

class Ajustes(models.Model):
    """docstring for ClassName"""
    uso_disco = models.IntegerField('Uso disco video' ,default=90)

    class Meta:
        verbose_name_plural = "Ajustes"

class Licencia(models.Model):
    fecha_caducidad = models.DateTimeField('Fecha de caducidad',auto_now_add=False,blank=True, null=True, )
    clave = models.TextField('clave',max_length=256)
        

mysite/camaras/views.py
# from django.http import StreamingHttpResponse
# import cv2
# import threading
# from django.views.decorators.gzip import gzip_page
#import imagezmq

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import get_user_model
from django.http import JsonResponse, HttpResponse
from .forms import CamarasForm, EventosForm
from .models import *
import pandas as pd
import base64
from django.conf import settings
import pytz
from django.db.models.functions import Trunc
import ffmpy
import os
from os import walk
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.timezone import make_aware , now
from django.forms.models import model_to_dict
from .vivotek import VivotekCamera
import json
from datetime import datetime

SCL = pytz.timezone(settings.TIME_ZONE)
#path = 'media/alarmas/'
path = '/var/www/mysite/media/alarmas/'

coco=['persona', 'bicicleta', 'auto', 'moto', 'avión', 'autobús', 'tren', 'camión', 'barco', 'semáforo', 'boca de incendios', 'señal de parada', 'parquímetro', 'banco', 'pájaro', 'gato', 'perro',
 'caballo', 'oveja', 'vaca', 'elefante', 'oso', 'cebra', 'jirafa', 'mochila', 'paraguas', 'bolso', 'corbata', 'maleta', 'frisbee', 'esquís','bola de nieve','pelota' 'cometa', 'bate',
  'guante de béisbol', 'patineta', 'tabla de surf', 'raqueta', 'botella', 'copa de vino', 'taza', 'tenedor', 'cuchillo', 'cuchara', 'tazón', 'banana', 'sándwich', 'manzana', 'naranja',
   'brócoli', 'zanahoria', 'hot dog', 'pizza', 'donut', 'pastel', 'silla', 'sofá', 'maceta', 'cama', 'maceta', 'comedor', 'inodoro', 'tvmonitor', 'laptop', 'mouse', 'teclado remoto',
    'teléfono', 'celular', 'horno', 'microondas', 'tostador', 'fregadero', 'refrigerador', 'libro', 'reloj', 'florero', 'tijeras', 'peluche', 'secador de pelo', 'cepillo de dientes','NA',"NA"]

def fformato(serie):
    #if  serie.dtype.str != '|O':
    serie=serie.dt.strftime('%d/%m/%Y %H:%M:%S')
    return serie

@login_required
def home(request):
    request.session.set_expiry(0) 
    return render(request, "home.html", {} )

@login_required
def camara(request,id):
    instance = get_object_or_404(Camara, pk=id)
    if request.method == 'POST':
        form = CamarasForm(request.POST, instance=instance)
        form.save()
        if form.is_valid():
            print("paso x aquí EnvioForm",)
            # redirect to a new URL:
            return redirect('lista_camaras')
        else:
            print(request.POST, form.is_valid())
    else:
        form = CamarasForm(instance=instance)
    imagen =  '<canvas id="canvas" width=608  height=608 style=" background: url(data:image/png;base64,%s) "></canvas>' % base64.b64encode(instance.image).decode("utf-8")
    campos = {
    'form': form,
    'imagen': imagen,
     }
    return render(request, 'camaras.html', campos)

@login_required
def lista_camaras(request):
    icono_true = '<a class="btn-floating green"><i class="material-icons">check_circle</i></a>'
    icono_false = '<a class="btn-floating pulse red"><i class="material-icons">close</i></a>'
    camaras = Camara.objects.all().order_by('id')
    df = pd.DataFrame(camaras.values('id','nombre',  'estado', 'sensib', 'fuente' ))
    df["estado"] = df["estado"].apply(lambda x: icono_true if x else icono_false)
    df["id"] = df["id"].apply(lambda x: '<a href="/camara/{0}">{0}</a>'.format(x))
    df.rename(columns={
        'nombre':'Nombre',
        'estado': 'Estado',
        'sensib': 'Sensibilidad',
        'fuente':'Fuente de video',
        }, inplace=True)
    html = df.to_html(index=False,
        escape=False,
        render_links=True,
        justify='center',
        classes=['table table-hover'],
        )
    return render(request, 'camaras_list.html', {'tabla':html})

#@login_required
def lista_alarmas(request):
    alarmas = Alarmas.objects.all().order_by('-tiempo')
    if len(alarmas):
        df = pd.DataFrame(alarmas.values('id','camara_id__nombre' ,'tiempo','clase','cantidad' ,'video', 'recibido',Fecha=Trunc('tiempo', 'second', tzinfo=SCL)))
        df['Fecha']=fformato(df['Fecha'])
        df["id"] = df["id"].apply(lambda x: '<a href="/video/{0}">{0}</a>'.format(x))
        df.rename(columns={
                'camara_id__nombre':'Cámara',
                'clase': 'Clases Objetos',
                'cantidad': 'Cantidad',
                }, inplace=True)
        df=df.drop(columns=['video', 'recibido','tiempo'])
        jtabla=df.to_json(orient='split', index=False,)
        col = []
        for i in df.columns:
            fo = {}
            fo["title"] = i
            col.append(fo)

        html = df.to_html(columns=['Cámara','Fecha','Cantidad','Clases Objetos','id'],
            index=False,
            escape=False,
            render_links=True,
            justify='center',
            classes=['table table-hover'],
            table_id='alarmas_id',
            max_rows=100,
            )
        content = {'tabla':html, 'jtabla':jtabla, 'col':col}
    else:
        content = {'info':'Sin información'}

    return render(request, 'alarmas_list.html', content)

def borra_alarmas(request):
    q = request.POST
    lista = q.getlist('coment[]')
    l1 = []
    for i in lista:
        l1.append(int(i))
    #print(type(l1),l1)
    selec = Alarmas.objects.filter(pk__in=l1)
    for i in selec.values('video'):
        #print(i['video'])
        try:
            os.remove(path + i['video'])
        except:
            print("error borrando",i['video'])
            pass
    selec.delete()
    borra_video_zombi()
    return redirect('/alarmas/')

def borra_video_zombi():
    lfiles = []
    lalarm = []
    alarmas = Alarmas.objects.all().order_by('-tiempo')
    for (dirpath, dirnames, filenames) in walk(path):
        lfiles.extend(filenames)
        break
    for a in alarmas:
        lalarm.append(a.video)
    for file in lfiles:
        if file not in lalarm:
            try:
                os.remove(path + file)
            except:
                print("error borrando",file)
                print(file,'no esta')


def video(request, id):
    alarma = Alarmas.objects.get(pk=id)
    file = path + alarma.video
    output = path + 'output.mp4'
    error_msg = ''
    try:
        os.remove(output)
    except:
        pass
    if os.path.isfile(file):
        
        try:
            ff = ffmpy.FFmpeg( inputs={file: None}, outputs={output: None} )
            ff.run()
        except:
            pass
            error_msg = 'error convirtiendo ffmpeg'
    else:
        error_msg = 'archivo %s no encontrado' %(file)
    video = '/media/alarmas/output.mp4'
    content = {
    'video':video,
     'id':alarma.id,
     'tiempo':alarma.tiempo,
     'camara':alarma.camara,
     'error_msg':error_msg,
     }
    return render(request, 'video.html', content)

@csrf_exempt
def cam_down(request):
    ''' vista que recibe las alarmas desde los workers o dockers (detector_multy)'''
    if request.method == 'POST':
        camara = request.POST['camara']
        fuente = request.POST['fuente']
        error_msg = request.POST['error_msg']
        secreto  = request.POST['secreto']
        if camara is not None:
            cam=Camara.objects.get(nombre=camara)
            if secreto == cam.secreto:
                txt = 'nodo %s sin señal de video de %s' % (camara,fuente)
                print(txt)
                cam.estado = False
                cam.error_msg = error_msg
                cam.save()
            else:
                print('Erro de validación en cam',cam.nombre)

    data = {
          "data": "data",
        }
    return JsonResponse(data, safe=False)

@csrf_exempt
def alarma_post(request):
    ''' vista que recibe las alarmas desde los workers o dockers (detector_multy)'''
    if request.method == 'POST':
        camara = request.POST['camara']
        tiempo = request.POST['tiempo']
        clase = request.POST['clase']
        cantidad = request.POST['cantidad']
        video = request.POST['video']
        secreto  = request.POST['secreto']
        if camara is not None:
            cam=Camara.objects.get(nombre=camara)
            if secreto == cam.secreto:
                #print('cam.secreto iguales en alarma_post',video)
                clases=[]
                clase = json.loads(clase)
                for c in clase:
                    #print(c,'c')
                    clases.append(coco[int(c)])
                nueva_alarma = Alarmas(
                                camara=cam,
                                tiempo=tiempo,
                                clase=clases,
                                cantidad=cantidad,
                                video=video)
                nueva_alarma.save()
                evento = Eventos.objects.filter(proced=True)
                #print("evento",evento)
                if len(evento)==0:
                    if cam.host != '0.0.0.0':
                        vivocam = VivotekCamera(host=cam.host,
                                 port=cam.port,
                                 usr=cam.usr,
                                 pwd=cam.pwd,
                                 digest_auth=cam.digest_auth,
                                 ssl=cam.ssl,
                                 verify_ssl=cam.verify_ssl,
                                 sec_lvl=cam.sec_lvl)
                        vivocam.do('do0',1)
            else:
                print('Erro de validación en cam',cam.nombre)

    data = {
          "data": "data",
        }
    return JsonResponse(data, safe=False)

@csrf_exempt
def camviva_post(request):
    ''' vista que recibe las alarmas desde los workers o dockers (detector_multy)'''
    if request.method == 'POST':
        camara = request.POST['camara']
        tiempo = request.POST['tiempo']
        image = request.POST['image']
        image=bytearray(image,'ISO-8859-1') 

mysite/templates/alarmas_list.html
{% extends 'base.html' %}
{% block content %}
<p></p>

<div class="container">
<h3>{{info}}</h3>
<div id="events2"></div>
<table id="test_table" class="display" width="100%"></table>
</div>

{% csrf_token %}
{% endblock %}
{% block jquery %}
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
    $('.loader').show();
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    },
      complete: function(){
     $('.loader').hide();
  },
  success: function() {
  //$('#loader').hide();
}
});
$.fn.dataTable.moment( 'DD/MM/YYYY HH:mm' );
var elegidos = [];
var json={{ jtabla | safe }};
var col = json["columns"];
console.log({{col|safe}});
var tabla =   $('#test_table').DataTable({
         data: json["data"],
        "columns": {{col|safe}},
        dom: 'Bfrtip',
        "language": {
        "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Spanish.json"
             },
        select: true,
        "order": [[ 1, "desc" ]],
        buttons: [
        {
            text: 'Selecciona todo',
            action: function () {
                tabla.rows().select();
            }
        },
        {
            text: 'Desselecionar',
            action: function () {
                tabla.rows().deselect();
            }
        },
        {
            text: 'Borrar selecionados',
            action: function() {
                if (confirm("¿Esta seguro de borrar los registros seleccionados?")) {
                var elegidos = [];
                var seleccion = tabla.rows( { selected: true } );
                var count = seleccion.count();
                var rowData = seleccion.data().toArray();
                rowData.forEach(function(item, index, array) {
                    let fila = item
                    fila = fila[0].split(">")[1].split("<")[0];
                    elegidos.push(fila);
                });
                console.log(elegidos);
                $.ajax({
                  type: "POST",
                  url: /borra_alarmas/,
                  data: {coment : elegidos,},
                  success: function(data){ 
                  location.reload();
                  console.log("OK")
                        },
                    });
                }
            }
        }
        ]
        } );

{% endblock %}

mysite/templates/camaras.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<p></p>
<div class="container">
    <div class="row">
        <div class='col-sm-6 py-1'> 
            <div class="form-group">
                <p></p>
                <form method="post" autocomplete="off">{% csrf_token %}
                    {{ form|crispy }}
                    <p></p>
                    <input type="submit" class="form-control btn btn-primary" value="Guardar">
                </form>
            </div>
            </div>
        <div class='col-sm-6 py-1'> 
            <br/>
            {{imagen|safe}}
            <br/><button id="clear" class="btn btn-outline-danger btn-sm">Limpiar</button>
            <button id="guardar" class="btn btn-outline-success btn-sm">Fijar</button>
        </div>
    </div>
</div>




<script> 
var vid = document.getElementById("myVideo"); 

function playVid() { 
  vid.play(); 
} 

function pauseVid() { 
  vid.pause(); 
} 
</script>

<!-- <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script> -->
{% endblock %}
    {% block jquery %}
$(function () {
        if ($("#id_areas").val()){
                var polyLines = JSON.parse($("#id_areas").val());
            } else {
                var polyLines = []
            }
        var canvas = document.getElementById("canvas"),
            ctx = canvas.getContext("2d"),
            offset = $("#canvas").offset(),
            storedLines = [],
            start = {x: 0, y: 0},
            radius = 7;
            draw();
            

        function canvasPosition(e) {
            return {
                x: parseInt(e.clientX - offset.left),
                y: parseInt(e.clientY - offset.top)
            };
        }

        $("#canvas").mousedown(function (e) {
            var pos = canvasPosition(e);
            if (hitStartCircle(pos)) {
                polyLines.push(storedLines);
                storedLines = [];
                draw();
            }
            else
            {
                storedLines.push(pos);
                update(pos);
            }
        })
        .mousemove(function (e) {
            update(canvasPosition(e));
        });

        // Draw completed polylines
        function draw() {
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            $.each(polyLines, function (idx, polyLine) {
                fillPolyline(polyLine);
            });
        }

        // Update shape currently being drawn
        function update(position) {
            var len = storedLines.length;
            if(len==0) return;

            draw();
            ctx.fillStyle = "green";
            ctx.beginPath();
            ctx.arc(storedLines[0].x, storedLines[0].y, radius, 0, 2 * Math.PI, false);
            ctx.fill();
            ctx.strokeStyle = "orange";
            ctx.lineWidth = 3;
            ctx.beginPath();
            ctx.moveTo(storedLines[0].x, storedLines[0].y);
            for(var i=1; i<len; ++i) {
                ctx.lineTo(storedLines[i].x, storedLines[i].y)
            }
            ctx.lineTo(position.x, position.y);
            ctx.stroke();


        };

        function hitStartCircle(pos) {
            var start = storedLines[0] || {x:0, y:0},
                dx = pos.x - start.x,
                dy = pos.y - start.y;
            return (dx * dx + dy * dy < radius * radius)
        }

        function fillPolyline(lines) {
            ctx.strokeStyle = "red";
            //ctx.fillStyle = "blue";
            ctx.lineWidth = 3;
            ctx.beginPath();
            ctx.moveTo(lines[0].x, lines[0].y);
            for (var i = 0; i < lines.length; i++) {
                ctx.lineTo(lines[i].x, lines[i].y);
            }
            ctx.closePath();
            //ctx.fill();
            ctx.stroke();

        }

        $("#clear").click(function () {
            polyLines = [];
            draw();
        });

        $("#guardar").click(function () {
            console.log('polyLines',polyLines);
            puntos = JSON.stringify(polyLines);
            $("#id_areas").val( puntos);
            $.each(polyLines, function(i, item) {
                console.log(item);
            });
            draw();
        });
});

{% endblock %}

mysite/templates/camaras_list.html
{% extends 'base.html' %}
{% block content %}
<!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/css/materialize.min.css"  media="screen,projection"/>
<div class="container">
	<p></p>
{{tabla|safe}}
</div>
      <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="/static/js/materialize.min.js"></script>

<script type="text/javascript">
    function updateTime(){window.location.reload(true);
        console.log('paso x aqui')
    }


setInterval(updateTime, 10000);
</script>
{% endblock %}

mysite/templates/email_alarma.html
{% load i18n %}
{% autoescape off %}

<p>Estimados,</p>  
<p>Este es un aviso de alarma.</p>


Muchas gracias.

El equipo de www.hrgestion.cl


{% endautoescape %}

mysite/templates/eventos_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/css/materialize.min.css"  media="screen,projection"/>



<div class="container py-2">
        <p></p>
    <h2>Lista de eventos</h2>
    <h3>{{info}}</h3>
{{tabla|safe}}
</div>

      <!--JavaScript at end of body for optimized loading-->
      <script type="text/javascript" src="/static/js/materialize.min.js"></script>

{% endblock %}

{% block jquery %}

{% endblock %}

mysite/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}



<div class="container">
 <h3> Bienvenido {{ user.first_name }} {{ user.last_name}}! </h3><p>usuario: {{ user.username}}</p>

<style type="text/css"> .alto{ height: 200px; }</style>

<section class="">

<div class="row align-items-center alto">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body btn-primary">
        <h5 style="color:white;" class="card-title">Cámaras</h5>
        <p class="card-text">Ajustes rápidos de cámaras.</p>
        <a  href="/camara" class="btn btn-light green">Ir a sección</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body btn-info">
        <h5 style="color:white;" class="card-title">Alarmas</h5>
        <p class="card-text">Listado de eventos registrados.</p>
        <a href="/alarmas/eventos" target="_blank" class="btn btn-dark red">Ir a sección</a>
      </div>
    </div>
  </div>
</div>

<!-- <div class="row align-items-center alto">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body btn-dark">
        <h5 style="color:white;" class="card-title">Análisis</h5>
        <p class="card-text">Sección de consulta de información y gráficos.</p>
        <a href="#" class="btn btn-light">Ir a sección</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6 ">
    <div class="card">
      <div class="card-body btn-info">
        <h5 style="color:white;" class="card-title">Archivo</h5>
        <p class="card-text">Repositorio virtual de documentación, ordenanzas, leyes y otros.</p>
        <a href="/archivos/menu/" class="btn btn-light">Ir a sección</a>
      </div>
    </div>
  </div>
</div> -->
</section>

</div>
{% else %}
 <h1>Bienvenido al portal CENTRAL</h1>
 <p>Lo invitamos a registrarse en el siguiente <a href="{% url 'signup' %}"   >enlace<a> <p>



{% endif %}


{% endblock %}


{% block jquery %}



{% endblock %}

mysite/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-secondary grey" type="submit">Login</button>
  </form>
{% endblock %}